const types = {
  CREATE_DECK_REQUEST: 'CREATE_DECK_REQUEST',
  CREATE_DECK_SUCCESS: 'CREATE_DECK_SUCCESS',
  CREATE_DECK_FAILURE: 'CREATE_DECK_FAILURE',
  LOAD_GAME_REQUEST: 'LOAD_GAME_REQUEST',
  LOAD_GAME_SUCCESS: 'LOAD_GAME_SUCCESS',
  LOAD_GAME_FAILURE: 'LOAD_GAME_FAILURE',

};

export default types;
